yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: pnp
pnpMode: loose
# Experimental as of Yarn 3.2.0.
# Replaces the need for `nodeLinker:node-modules` on some projects.
# Once stable, leave it as default.
pnpEnableEsmLoader: false
pnpFallbackMode: all
enableScripts: false
supportedArchitectures:
  os:
    - "current"
    - "linux"

logFilters:
  # Disable the warnings when peer dependencies are not provided due to boilerplate.
  - code: YN0002
    level: discard
  # Disable warning of third party build scripts we don't let run.
  - code: YN0004
    level: discard
