// Autogenerated by typings-for-css-modules-loader.
declare namespace TransformNoticePcssNamespace {
	export interface ITransformNoticePcss {
		wrap: string;
	}
}

declare const TransformNoticePcssModule: TransformNoticePcssNamespace.ITransformNoticePcss;

export = TransformNoticePcssModule;
