#!/bin/bash

#####################################################################################
#
# Run yarn dist to build the plugin after making a commit.
#
# @version 5.2.0
#
#####################################################################################

source /e/scripts/git/hooks/version-1/post-commit-plugin
