#!/bin/bash

#####################################################################################
#
# Get our local environment's dependencies up to date when merging a branch.
#
# Customized for this plugin to only run `yarn dist`
#
# @version 5.2.0
#
#####################################################################################

source /e/scripts/git/hooks/version-1/post-merge-plugin
