#!/bin/bash

#####################################################################################
#
# Runs the `post-merge` hook when a new branch is checked out.
#
# @version 1.0.1
#
#####################################################################################

DIR="$(cd "$(dirname "$(realpath "$0")}")" >/dev/null && pwd)"
exec $DIR/post-merge
