#!/bin/bash

#####################################################################################
#
# Runs the `post-merge` hook when a new branch is checked out.
#
# @version 1.1.0
#
#####################################################################################

source /e/scripts/git/hooks/version-1/post-checkout
