// Autogenerated by typings-for-css-modules-loader.
declare namespace InfoPanelPcssNamespace {
	export interface IInfoPanelPcss {
		button: string;
		wrap: string;
	}
}

declare const InfoPanelPcssModule: InfoPanelPcssNamespace.IInfoPanelPcss;

export = InfoPanelPcssModule;
