// Autogenerated by typings-for-css-modules-loader.
declare namespace PreviewPcssNamespace {
	export interface IPreviewPcss {
		error: string;
		placeholder: string;
		spin: string;
		'spin-content': string;
		'spin-wrap': string;
		spinContent: string;
		spinWrap: string;
		wrap: string;
	}
}

declare const PreviewPcssModule: PreviewPcssNamespace.IPreviewPcss;

export = PreviewPcssModule;
