<?php 
/**
 * The Ouput of the Advanced Sidebar Page Widget
 *
 * @author Mat Lipe
 * @deprecated 3.1.13
 *
 * @see views/page_list.php which is the files used when not using legacy mode
 *
 * @example to edit, create a file named page_list.php and put in a folder in the your theme called 'advanced-sidebar-menu.
 *          Copy the contents of the file into that file and edit at will.
 *          Select Legacy in the widget options.
 * @notice  Do not edit this file in its original location or it will break on upgrade
 */


/** @var advancedSidebarMenu $asm */
$asm->title();

#-- list the parent page if chosen
if( $asm->include_parent() ){
	echo '<ul class="parent-sidebar-menu" >';
			 wp_list_pages("post_type=".$asm->post_type."&sort_column=$asm->order_by&title_li=&echo=1&depth=1&include=".$asm->top_id);
}


//If there are children start the Child Sidebar Menu
if( $child_pages ){
	echo '<ul class="child-sidebar-menu">';

	#-- If they want all the pages displayed always
	if( $asm->display_all() ){

		wp_list_pages("post_type=".$asm->post_type."&sort_column=$asm->order_by&title_li=&echo=1&child_of=".$asm->top_id."&depth=".$instance['levels']."&exclude=".$instance['exclude']);
	} else {

		#-- Display children of current page's parent only
		foreach($child_pages as $pID){

				#-- If the page is not in the excluded ones
			if( $asm->is_excluded( $pID ) ){
					#--echo the current page from the $result
				wp_list_pages("post_type=".$asm->post_type."&sort_column=$asm->order_by&title_li=&echo=1&depth=1&include=".$pID);
			}

			#-- if the link that was just listed is the current page we are on
			if( $asm->page_ancestor( $pID ) ){

				//Get the children of this page
				$grandkids = $asm->page_children($pID);
				if( $grandkids ){
					#-- Create a new menu with all the children under it
					echo '<ul class="grandchild-sidebar-menu">';
							wp_list_pages("post_type=".$asm->post_type."&sort_column=$asm->order_by&title_li=&echo=1&exclude=".$instance['exclude']."&child_of=".$pID);

					echo '</ul>';
				}
			}
		}
	}

	#-- Close the First Level menu
	echo '</ul><!-- End child-sidebar-menu -->';

}
if( $asm->include_parent() ) {
	echo '</ul><!-- .parent-sidebar-menu -->';
}
		


	
