// Autogenerated by typings-for-css-modules-loader.
declare namespace EditPcssNamespace {
	export interface IEditPcss {
		error: string;
	}
}

declare const EditPcssModule: EditPcssNamespace.IEditPcss;

export = EditPcssModule;
