name: Deploy to WordPress.org
env:
  # Can't specify VERSION, or the plugin will deploy in that version.  
  # VERSION: 3.3.0
  NODE_VERSION: '20.11.0'
  PHP_VERSION: '8.3'
  TZ: 'America/Chicago'

on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{env.PHP_VERSION}}
      - name: Install yarn
        shell: bash
        run: corepack enable
      - name: Install ts-node
        shell: bash
        run: npm install -g ts-node
      - name: Compile JS
        shell: bash
        run: cd ${{github.workspace}} && yarn dist
      - name: Generate JS translations
        shell: bash
        run: cd ${{github.workspace}}/dev/translate-cli && composer install && php command.php
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
