name: Deploy to WordPress.org
env:
  VERSION: 2.1.0
  NODE_VERSION: '16.14.2'
  PHP_VERSION: '8.0'

on:
  push:
    branches:
      - feature/625625414772799/gutenberg-blocks

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'feature/625625414772799/gutenberg-blocks'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{env.PHP_VERSION}}
      - name: Install yarn
        shell: bash
        run: npm i -g yarn
      - name: Compile JS
        shell: bash
        run: cd ${{github.workspace}}/js && yarn dist
      - name: Generate JS translations
        shell: bash
        run: cd ${{github.workspace}}/dev/translate-cli && php command.php
      - name: List files
        shell: bash
        run: rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" trunk/ --list-only
