name: Deploy to WordPress.org
env:
  # Can't specify VERSION, or the plugin will deploy in that version.  
  # VERSION: 2.1.0
  NODE_VERSION: '16.19.0'
  PHP_VERSION: '8.1'
  TZ: 'America/Chicago'

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test root directory change'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{env.PHP_VERSION}}
      - name: Install yarn
        shell: bash
        run: npm i -g yarn
      - name: Compile JS
        shell: bash
        run: cd ${{github.workspace}} && yarn dist
      - name: Generate JS translations
        shell: bash
        run: cd ${{github.workspace}}/dev/translate-cli && composer install && php command.php
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        width:
          dry-run: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
