###################################################
# Install and cache the dependencies when `master` is pushed
# for other workflows to use.
#
# Most workflows will reuse the same cached
# dependencies as the last release. Having master populate the
# cache makes them accessible to all pull requests and deployments.
#
# Variables must be set in the calling repository.
# https://github.com/lipemat/advanced-sidebar-menu/settings/variables/actions
# @see The reusable workflow for the required variables.
#
# @version 1.1.1
#
###################################################

name: Populate Caches

permissions:
  actions: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  populate:
    name: Populate all caches
    uses: lipemat/public-actions/.github/workflows/populate-caches-plugin.yml@version/1
