############################################################
# Test and lint files in a pull request.
#
# Variables must be set in the calling repository.
# https://github.com/lipemat/advanced-sidebar-menu/settings/variables/actions
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   NODE_VERSION: The version of Node to install.
#   PHPCS_VERSION: The version of `lipemat/wp-phpcs` to install.
#   PRO: The pro plugin slug.
#   PRO_BRANCH: The branch of the pro plugin.
# secrets:
#   PUBLIC_ACTIONS_PRO_REPO: The token to access the pro repository.
#
# @version 0.1.0
#
############################################################

name: Test & Lint Files

permissions:
  actions: read
  contents: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  php-lint:
    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1, 8.2, 8.3, 8.4 ]
    uses: lipemat/public-actions/.github/workflows/php-lint.yml@version/1
    with:
      php: ${{ matrix.php }}
  
  wp-unit:
    strategy:
      # https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
      matrix:
        versions: [
          {
            php: 7.4,
            wp: 6.2.6
          },
          {
            php: 8.1,
            wp: 6.2.6
          },
          {
            php: 7.4,
            wp: 6.8.2
          },
          {
            php: 8.4,
            wp: 6.8.2
          },
        ]
        multisite: [ 'multisite' ]
    uses: lipemat/public-actions/.github/workflows/wp-unit-plugin.yml@version/1
    with:
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.versions.php }}
      skipDatabaseInstall: false
      wp: ${{ matrix.versions.wp }}
    secrets: inherit
  
  phpstan:
    strategy:
      matrix:
        combination:
          - php: 7.4
            phpstan-version: 3.4.2
            stubs: 6.2.6
          - php: 8.4
            stubs: 6.8.1
    uses: lipemat/public-actions/.github/workflows/phpstan-plugin.yml@version/1
    with:
      php: ${{ matrix.combination.php }}
      phpstan-version: ${{ matrix.combination.phpstan-version }}
      stubs: ${{ matrix.combination.stubs }}
    secrets: inherit
  
  phpcs:
    uses: lipemat/public-actions/.github/workflows/phpcs-plugin.yml@version/1
  
  js-unit:
    uses: lipemat/public-actions/.github/workflows/js-unit-plugin.yml@version/1
    secrets: inherit
